services:
  app:
    build:
      context: .
      target: php
      args:
        PHP_VERSION: 8.2
        COMPOSER_VERSION: 2.5
        EXTENSION_INSTALLER_VERSION: 2.1
    command: ["composer", "install", "--no-interaction"]
    environment:
      XDEBUG_MODE: coverage
#      XDEBUG_MODE: debug
#      XDEBUG_CONFIG: "profiler_enable=on idekey=PHPSTORM client_host=host.docker.internal"
    volumes:
      - ./:/app:delegate