name: CI

on:
  push: ~
  workflow_dispatch: ~

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - # Copies the repository files to the Action Runner
        name: Checkout Repository
        uses: actions/checkout@v3

      - # Installs PHP and other necessary tools
        name: Setup PHP
        uses: shivammathur/setup-php@2.25.4
        with:
          php-version: 8.2

      - # Installs and caches PHP dependencies 
        name: Install Dependencies
        uses: ramsey/composer-install@2.2.0

      - # Validates composer.json structure and required fields
        name: Validate composer.json
        run: composer validate --ansi --strict --no-check-publish

      - # Runs code quality tools, like phpstan etc.
        name: Run Code Quality Tools
        run: composer analyse

      - # Runs unit and integration tests, like phpspec, phpunit etc.
        name: Run Tests
        run: composer test

      - # Run AsyncAPI Validation
        name: AsyncAPI Validation
        run: docker run --rm -v $(pwd):/app asyncapi/cli:0.54.3 validate /app/asyncapi.yaml
